/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.VeterinarioControlador;
import dto.MascotaDTO;
import java.util.ArrayList;
import modelo.Veterinario;
import utiles.Generator;
import dto.veterinarioDTO;
import java.util.List;
import javax.swing.JOptionPane;
import dto.ConsultaDTO;
import java.time.LocalDate;
import dto.DtoMedicina;
import controladores.ControladorMedicina;
import javax.swing.table.DefaultTableModel;
import controladores.MascotaControlador;
import dto.VacunaDTO;
import javax.accessibility.AccessibleRole;
/**
 *
 * @author Juanes Cardona
 */
public class VentanaCita extends javax.swing.JFrame {
    
    private VeterinarioControlador vetControlador;
    private ControladorMedicina controladorMedicina;
    private MascotaControlador mascotaControlador;
    private VentanaServicios menu;
   
    /**
     * Creates new form VentaCita
     */
    public VentanaCita(VentanaServicios menu) {
        this.menu = menu;
        initComponents();
        this.controladorMedicina = new ControladorMedicina();
        this.vetControlador = new VeterinarioControlador();
        this.mascotaControlador = new MascotaControlador();
        cargarVet();
        tablaCons.setModel(new DefaultTableModel(
            new Object[][]{},
            new String[]{"Fecha","Codigo","ID", "Nombre Mascota", "Documento Propietario", "Diagnostico", "Tratamiento"} ));

    }
    private void limpiarCamposCons(){
    txtDiagnostico.setText("");
    txtIdMas.setText("");
    txtTratamiento.setText("");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblNomMas = new javax.swing.JLabel();
        lblDiagnostico = new javax.swing.JLabel();
        lblTratamiento = new javax.swing.JLabel();
        txtIdMas = new javax.swing.JTextField();
        txtDiagnostico = new javax.swing.JTextField();
        txtTratamiento = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        lblNomMas1 = new javax.swing.JLabel();
        comboboxVet = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCons = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        bttBuscar = new javax.swing.JButton();
        lblNomMas2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelTitulo.setBackground(new java.awt.Color(0, 255, 102));

        lblTitulo.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Consulta");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        lblNomMas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNomMas.setText("Veterinarios:");

        lblDiagnostico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDiagnostico.setText("Diagnostico");

        lblTratamiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTratamiento.setText("Tratamiento");

        txtIdMas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtDiagnostico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtTratamiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnRegistrar.setBackground(java.awt.Color.gray);
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(java.awt.Color.gray);
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnMenu.setBackground(java.awt.Color.gray);
        btnMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        lblNomMas1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNomMas1.setText("Id Mascota");

        comboboxVet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tablaCons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaCons);

        btnEditar.setBackground(java.awt.Color.gray);
        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(java.awt.Color.gray);
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(java.awt.Color.gray);
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        bttBuscar.setBackground(java.awt.Color.gray);
        bttBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bttBuscar.setText("Buscar");
        bttBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttBuscarActionPerformed(evt);
            }
        });

        lblNomMas2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNomMas2.setText("Digite el codigo de la consulta a gestionar:");

        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNomMas1)
                        .addGap(85, 85, 85)
                        .addComponent(txtIdMas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomMas, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDiagnostico)
                            .addComponent(comboboxVet, 0, 281, Short.MAX_VALUE)
                            .addComponent(txtTratamiento))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrar)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lblNomMas2)
                        .addGap(29, 29, 29)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdMas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomMas1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomMas)
                            .addComponent(comboboxVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDiagnostico)
                            .addComponent(txtDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTratamiento)
                            .addComponent(txtTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnMenu)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegistrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttBuscar)
                    .addComponent(lblNomMas2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnActualizar))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargarVet() {
    comboboxVet.removeAllItems(); // Limpieza recomendada
    comboboxVet.addItem("Seleccione una opción");

        ArrayList<veterinarioDTO> veterinarios = vetControlador.getVeterinarios();
    
    for (veterinarioDTO vet : veterinarios) {
        String txt = vet.getNombre() + "-" + vet.getEspecialidad();
        comboboxVet.addItem(txt);
    }
}
    
    public void listarConsultasTabla() {
    DefaultTableModel modelo = (DefaultTableModel) tablaCons.getModel();
    modelo.setRowCount(0); // Limpiar tabla

    ArrayList<ConsultaDTO> consultas = controladorMedicina.getConsultas();

    for (ConsultaDTO consulta : consultas) {
        Object[] fila = {
            consulta.getFecha(),                   
            consulta.getCodigo(),                  
            consulta.getIdMas(),
            consulta.getNomMascota(),
            consulta.getDocProp(),    
            consulta.getDiagnostico(),             
            consulta.getTratamiento()              
        };
        modelo.addRow(fila);
    }

    tablaCons.setModel(modelo);
}
    
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
 try {
        String idMas = txtIdMas.getText().trim();
        String diagnostico = txtDiagnostico.getText().trim();
        String tratamiento = txtTratamiento.getText().trim();
        String codigo = Generator.generarCodigoConsulta();
        String fecha = LocalDate.now().toString();
        if (idMas.isEmpty() ||  diagnostico.isEmpty() || tratamiento.isEmpty() || codigo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

    // Validar que el nombre solo contenga letras (y espacios opcionalmente)
    if (!diagnostico.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+")) {
        JOptionPane.showMessageDialog(this, "El diagnostico debe contener solo letras.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
     if (!tratamiento.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+")) {
        JOptionPane.showMessageDialog(this, "El tratamiento debe contener solo letras.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    } 
        
        MascotaDTO buscar = mascotaControlador.buscarMascotaPorId(idMas);
        
        if(buscar == null){
            JOptionPane.showMessageDialog(this, "no se puede registrar una consulta sin una mascota previamente registrada");
            return;
        }
        String docprop = buscar.getDocumentoProp();
        
        DtoMedicina nuevo = controladorMedicina.buscarMedicinaPorcodigo(codigo);
            
        if(nuevo != null){
            JOptionPane.showMessageDialog(this, "Ya existe una consulta con el codigo: "+ codigo );
            return;
        }
        docprop = buscar.getDocumentoProp();
        ConsultaDTO cons = new ConsultaDTO(diagnostico, tratamiento, codigo, fecha, idMas, docprop, buscar.getNombre());
        boolean exito = controladorMedicina.registrarMedicina(cons);

        if (exito) {    
            JOptionPane.showMessageDialog(this, "consulta registrado correctamente.");
            listarConsultasTabla();
            limpiarCamposCons();
          
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo registrar la consulta.");
        }

    } catch (IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

        
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCamposCons();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        menu.setVisible(true);
        
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
         String codigo = txtCodigo.getText().trim();

    if (codigo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debes ingresar un código para editar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    DtoMedicina medicina = controladorMedicina.buscarMedicinaPorcodigo(codigo);

    if (medicina == null) {
        JOptionPane.showMessageDialog(this, "No se encontró ninguna medicina con ese código.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (medicina instanceof ConsultaDTO consulta) {
        String nuevoDiagnostico = JOptionPane.showInputDialog(this, "Nuevo diagnóstico:", consulta.getDiagnostico());
        if (nuevoDiagnostico == null) return;

        String nuevoTratamiento = JOptionPane.showInputDialog(this, "Nuevo tratamiento:", consulta.getTratamiento());
        if (nuevoTratamiento == null) return;

        consulta.setDiagnostico(nuevoDiagnostico);
        consulta.setTratamiento(nuevoTratamiento);

        controladorMedicina.editarMedicina(consulta);

        JOptionPane.showMessageDialog(this, "Consulta actualizada correctamente.");
        txtDiagnostico.setText(nuevoDiagnostico);
        txtTratamiento.setText(nuevoTratamiento);
        listarConsultasTabla();
    } else {
        JOptionPane.showMessageDialog(this, "Solo puedes editar consultas.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
         String codigo = txtCodigo.getText().trim();

    if (codigo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debes ingresar un código para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    DtoMedicina medicina = controladorMedicina.buscarMedicinaPorcodigo(codigo);

    if (medicina == null) {
        JOptionPane.showMessageDialog(this, "No se encontró ninguna medicina con ese código.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar la medicina con código: " + codigo + "?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

    if (confirmacion == JOptionPane.YES_OPTION) {
        controladorMedicina.eliminarMedicina(codigo);
        JOptionPane.showMessageDialog(this, "Medicina eliminada exitosamente.");
        listarConsultasTabla();
        limpiarCamposCons();
        comboboxVet.setSelectedIndex(-1);
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        listarConsultasTabla();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void bttBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttBuscarActionPerformed
        // TODO add your handling code here:
         String codigo = txtCodigo.getText().trim();

    if (codigo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debes ingresar un código para buscar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    DtoMedicina medicina = controladorMedicina.buscarMedicinaPorcodigo(codigo);

    if (medicina == null) {
        JOptionPane.showMessageDialog(this, "No se encontró ninguna medicina con ese código.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (medicina instanceof ConsultaDTO consulta) {
        MascotaDTO mascota = mascotaControlador.buscarMascotaPorId(consulta.getIdMas());

        txtIdMas.setText(consulta.getIdMas());
        txtDiagnostico.setText(consulta.getDiagnostico());
        txtTratamiento.setText(consulta.getTratamiento());
        txtCodigo.setText(consulta.getCodigo());

        String especie = mascota.getEspecie().trim().toLowerCase();
        for (int i = 0; i < comboboxVet.getItemCount(); i++) {
            String item = comboboxVet.getItemAt(i).toString().trim().toLowerCase();
            if (item.equals(especie)) {
                comboboxVet.setSelectedIndex(i);
                break;
            }
        }
    } else if (medicina instanceof VacunaDTO) {
        JOptionPane.showMessageDialog(this, "El código ingresado pertenece a una vacuna, no a una consulta.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "Tipo de medicina desconocido.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_bttBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton bttBuscar;
    private javax.swing.JComboBox<String> comboboxVet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDiagnostico;
    private javax.swing.JLabel lblNomMas;
    private javax.swing.JLabel lblNomMas1;
    private javax.swing.JLabel lblNomMas2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTratamiento;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JTable tablaCons;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDiagnostico;
    private javax.swing.JTextField txtIdMas;
    private javax.swing.JTextField txtTratamiento;
    // End of variables declaration//GEN-END:variables
}
