/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import modelo.Mascota;
import controladores.MascotaControlador;
import controladores.PropietarioControlador;
import utiles.Generator;
import dto.MascotaDTO;
import dao.MascotaDAO;
import dao.PropietarioDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import vistas.VentanaMenu;
import controladores.MascotaControlador;
import dto.PropietarioDTO;
import java.util.ArrayList;

/*
 *
 * @author Juanes Cardona
 */
public class VentanaRegistro extends javax.swing.JFrame {

    private VentanaMenu ventanaMenu;

    DefaultTableModel dtm = new DefaultTableModel();

    private MascotaControlador controladorMascota;
    private PropietarioControlador controladorPropietario;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaRegistro(VentanaMenu ventanaMenu) {
        this.ventanaMenu = ventanaMenu;
        this.controladorMascota = new MascotaControlador();
        this.controladorPropietario = new PropietarioControlador();
        initComponents();
        setLocationRelativeTo(this);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setVisible(true);
        setVisible(false);
        tblMascota.setModel(new DefaultTableModel(
            new Object[][]{},
            new String[]{"ID", "Nombre", "Especie", "Edad", "Documento Propietario"}
        ));
        
    }
private void cargarListaMascotas() {
    DefaultTableModel modelo = (DefaultTableModel) tblMascota.getModel();
    modelo.setRowCount(0); // Limpiar tabla antes de cargar

    ArrayList<MascotaDTO> mascotas = controladorMascota.obtenerMascotas();

    for (MascotaDTO mascota : mascotas) {
        modelo.addRow(new Object[]{
            mascota.getId(),
            mascota.getNombre(),
            mascota.getEspecie(),
            mascota.getEdad(),
            mascota.getDocumentoProp()
        });
    }
}
private void cargarListaPropietarios() {
    DefaultTableModel modelo = (DefaultTableModel) tablaProp.getModel();
    modelo.setRowCount(0); // Limpiar tabla

    ArrayList<PropietarioDTO> propietarios = controladorPropietario.obtenerPropietarios();

    for (PropietarioDTO p : propietarios) {
        modelo.addRow(new Object[]{
            p.getDocumento(),
            p.getNombre(),
            p.getTelefono(),
        });
    }
}
    
    private void limpiarCamposPropietario() {
    txtDocumentoPro.setText("");
    txtNombrePro.setText("");
    txtTelefonoPro.setText("");
}
private void limpiarCamposMas() {
    txtNombre.setText("");
    txtEspecie.setText("");
    txtEdad.setText("");
    txtDocuPropMAS.setText("");
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTituloRe = new javax.swing.JPanel();
        lblRegistroClinica = new javax.swing.JLabel();
        sprTitulo = new javax.swing.JSeparator();
        tbbPanelUsuario = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblInfPropietario = new javax.swing.JLabel();
        lblNombrePro = new javax.swing.JLabel();
        txtNombrePro = new javax.swing.JTextField();
        lblDocumentoPro = new javax.swing.JLabel();
        txtDocumentoPro = new javax.swing.JTextField();
        lblTelefonoPro = new javax.swing.JLabel();
        txtTelefonoPro = new javax.swing.JTextField();
        btnGuardaRegistro1 = new javax.swing.JButton();
        panelRegistro = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        lblInfMascota = new javax.swing.JLabel();
        btnGuardaRegistro = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblEspecie = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtEspecie = new javax.swing.JTextField();
        lblEdad = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtDocuPropMAS = new javax.swing.JTextField();
        panelUsuarios = new javax.swing.JPanel();
        lblBuscaMascota = new javax.swing.JLabel();
        lblIdBusc = new javax.swing.JLabel();
        lblBusNombre = new javax.swing.JLabel();
        lblBusEspecie = new javax.swing.JLabel();
        lblBusEdad = new javax.swing.JLabel();
        txtBusId = new javax.swing.JTextField();
        txtBusNombre = new javax.swing.JTextField();
        txtBusEspecie = new javax.swing.JTextField();
        txtBusEdad = new javax.swing.JTextField();
        btnActualizarMas = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMascota = new javax.swing.JTable();
        btnEliminar1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProp = new javax.swing.JTable();
        btnActualizarProp = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema De Gestion Clínica Veterinaria");

        panelTituloRe.setBackground(new java.awt.Color(0, 255, 102));

        lblRegistroClinica.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 36)); // NOI18N
        lblRegistroClinica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistroClinica.setText("Registro Clinica");

        sprTitulo.setBackground(new java.awt.Color(0, 153, 153));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        lblInfPropietario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfPropietario.setText("Información Propietario :");

        lblNombrePro.setText("Nombre :");

        lblDocumentoPro.setText("Documento :");

        lblTelefonoPro.setText("Telefono :");

        btnGuardaRegistro1.setBackground(java.awt.Color.gray);
        btnGuardaRegistro1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGuardaRegistro1.setText("Guardar Registro");
        btnGuardaRegistro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardaRegistro1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombrePro, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDocumentoPro)
                    .addComponent(lblTelefonoPro))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblInfPropietario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(224, 224, 224))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombrePro, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                            .addComponent(txtDocumentoPro)
                            .addComponent(txtTelefonoPro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btnGuardaRegistro1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblInfPropietario)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombrePro)
                    .addComponent(txtNombrePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocumentoPro)
                    .addComponent(btnGuardaRegistro1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocumentoPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoPro)
                    .addComponent(txtTelefonoPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        tbbPanelUsuario.addTab("Registrar Propietario", jPanel1);

        panelRegistro.setBackground(new java.awt.Color(0, 153, 153));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblInfMascota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfMascota.setText("Información Mascota :");

        btnGuardaRegistro.setBackground(java.awt.Color.gray);
        btnGuardaRegistro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGuardaRegistro.setText("Guardar Registro");
        btnGuardaRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardaRegistroActionPerformed(evt);
            }
        });

        lblNombre.setText("Nombre :");

        lblEspecie.setText("Especie :");

        lblEdad.setText("Edad :");

        jLabel1.setText("Documentoprop");

        javax.swing.GroupLayout panelRegistroLayout = new javax.swing.GroupLayout(panelRegistro);
        panelRegistro.setLayout(panelRegistroLayout);
        panelRegistroLayout.setHorizontalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistroLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelRegistroLayout.createSequentialGroup()
                                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRegistroLayout.createSequentialGroup()
                                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEdad, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                                    .addComponent(txtEspecie)
                                    .addComponent(txtDocuPropMAS))))
                        .addGap(81, 81, 81))
                    .addGroup(panelRegistroLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(lblInfMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardaRegistro)
                .addContainerGap())
        );
        panelRegistroLayout.setVerticalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblInfMascota)
                .addGap(34, 34, 34)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEspecie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEdad)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDocuPropMAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGuardaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        tbbPanelUsuario.addTab("Registrar Mascota", panelRegistro);

        panelUsuarios.setBackground(new java.awt.Color(0, 153, 153));

        lblBuscaMascota.setText("Busca Mascota");

        lblIdBusc.setText("Id :");

        lblBusNombre.setText("Nombre :");

        lblBusEspecie.setText("Especie :");

        lblBusEdad.setText("Edad :");

        btnActualizarMas.setBackground(java.awt.Color.gray);
        btnActualizarMas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnActualizarMas.setText("Actualizar");
        btnActualizarMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarMasActionPerformed(evt);
            }
        });

        btnEditar.setBackground(java.awt.Color.gray);
        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(java.awt.Color.gray);
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblMascota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMascota);

        btnEliminar1.setBackground(java.awt.Color.gray);
        btnEliminar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar1.setText("Eliminar");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUsuariosLayout = new javax.swing.GroupLayout(panelUsuarios);
        panelUsuarios.setLayout(panelUsuariosLayout);
        panelUsuariosLayout.setHorizontalGroup(
            panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuariosLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelUsuariosLayout.createSequentialGroup()
                        .addComponent(lblBusEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBusEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar1))
                    .addGroup(panelUsuariosLayout.createSequentialGroup()
                        .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUsuariosLayout.createSequentialGroup()
                                .addComponent(lblBusNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBusNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblBuscaMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelUsuariosLayout.createSequentialGroup()
                                .addComponent(lblIdBusc, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBusId, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelUsuariosLayout.createSequentialGroup()
                        .addComponent(lblBusEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBusEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizarMas)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelUsuariosLayout.setVerticalGroup(
            panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuariosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblBuscaMascota)
                .addGap(18, 18, 18)
                .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdBusc)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBusNombre)
                    .addComponent(txtBusNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar))
                .addGap(16, 16, 16)
                .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBusEspecie)
                    .addComponent(txtBusEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar1))
                .addGap(21, 21, 21)
                .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBusEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarMas))
                .addGap(108, 108, 108))
            .addGroup(panelUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbbPanelUsuario.addTab("Usuarios", panelUsuarios);

        tablaProp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaProp);

        btnActualizarProp.setBackground(java.awt.Color.gray);
        btnActualizarProp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnActualizarProp.setText("Actualizar");
        btnActualizarProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPropActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(btnActualizarProp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnActualizarProp)
                .addGap(221, 221, 221))
        );

        tbbPanelUsuario.addTab("Gestion de Propietarios", jPanel2);

        btnMenu.setBackground(java.awt.Color.gray);
        btnMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTituloReLayout = new javax.swing.GroupLayout(panelTituloRe);
        panelTituloRe.setLayout(panelTituloReLayout);
        panelTituloReLayout.setHorizontalGroup(
            panelTituloReLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistroClinica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sprTitulo, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelTituloReLayout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(btnMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelTituloReLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbbPanelUsuario)
                .addContainerGap())
        );
        panelTituloReLayout.setVerticalGroup(
            panelTituloReLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloReLayout.createSequentialGroup()
                .addComponent(lblRegistroClinica, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sprTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbbPanelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnMenu)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTituloRe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTituloRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ventanaMenu.setVisible(true);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
   
        

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnActualizarMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarMasActionPerformed
cargarListaMascotas();
        
    }//GEN-LAST:event_btnActualizarMasActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
  

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardaRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardaRegistroActionPerformed
   
          try {
               int cantidadActual = controladorMascota.obtenerMascotas().size();
               Generator.inicializarContadorMascota(cantidadActual);

    // 🔁 2. Ahora sí, genera el ID (empezará desde M{cantidadActual + 1})
              String idGenerado = Generator.generarCodigoMascota();
              
            String nombre = txtNombre.getText();
            String especie = txtEspecie.getText();
            String edad = txtEdad.getText();
            String documento = txtDocuPropMAS.getText();
            

       if ( nombre.isEmpty() || especie.isEmpty() || edad.isEmpty() || documento.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor complete todos los campos.", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
        return;
    }
            PropietarioDTO exito = controladorPropietario.buscarPropietarioPorDocumento(documento);
           
            if (exito == null) {
           JOptionPane.showMessageDialog(null, "No se pude registrar la mascota si no existe un Propietario.");
           return;
            }
                MascotaDTO nueva = new MascotaDTO(idGenerado, nombre, especie, edad, documento);
                boolean confirmar = controladorMascota.registrarMascota(nueva);
                if(confirmar){
                JOptionPane.showMessageDialog(null, "Mascota registrada correctamente.");
                cargarListaMascotas();
                }else{
                
                JOptionPane.showMessageDialog(null, "No se pudo registrar la mascota.");
                }
         
        }catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnGuardaRegistroActionPerformed

    private void btnGuardaRegistro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardaRegistro1ActionPerformed

    try {
        String documento = txtDocumentoPro.getText().trim();
        String nombre = txtNombrePro.getText().trim();
        String telefono = txtTelefonoPro.getText().trim();

        if (documento.isEmpty() || nombre.isEmpty() || telefono.isEmpty() ) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        PropietarioDTO nuevo = new PropietarioDTO(documento, telefono, nombre);
        boolean exito = controladorPropietario.registrarPropietario(nuevo);

        if (exito) {    
            JOptionPane.showMessageDialog(this, "Propietario registrado correctamente.");
            limpiarCamposPropietario();
            cargarListaPropietarios() ;
          //  cargarListaPropietarios(); // si tienes una tabla de propietarios
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo registrar el propietario.");
        }

    } catch (IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

      
    }//GEN-LAST:event_btnGuardaRegistro1ActionPerformed

    private void btnActualizarPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPropActionPerformed
cargarListaPropietarios();
    }//GEN-LAST:event_btnActualizarPropActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarMas;
    private javax.swing.JButton btnActualizarProp;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnGuardaRegistro;
    private javax.swing.JButton btnGuardaRegistro1;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBusEdad;
    private javax.swing.JLabel lblBusEspecie;
    private javax.swing.JLabel lblBusNombre;
    private javax.swing.JLabel lblBuscaMascota;
    private javax.swing.JLabel lblDocumentoPro;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEspecie;
    private javax.swing.JLabel lblIdBusc;
    private javax.swing.JLabel lblInfMascota;
    private javax.swing.JLabel lblInfPropietario;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombrePro;
    private javax.swing.JLabel lblRegistroClinica;
    private javax.swing.JLabel lblTelefonoPro;
    private javax.swing.JPanel panelRegistro;
    private javax.swing.JPanel panelTituloRe;
    private javax.swing.JPanel panelUsuarios;
    private javax.swing.JSeparator sprTitulo;
    private javax.swing.JTable tablaProp;
    private javax.swing.JTabbedPane tbbPanelUsuario;
    private javax.swing.JTable tblMascota;
    private javax.swing.JTextField txtBusEdad;
    private javax.swing.JTextField txtBusEspecie;
    private javax.swing.JTextField txtBusId;
    private javax.swing.JTextField txtBusNombre;
    private javax.swing.JTextField txtDocuPropMAS;
    private javax.swing.JTextField txtDocumentoPro;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEspecie;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombrePro;
    private javax.swing.JTextField txtTelefonoPro;
    // End of variables declaration//GEN-END:variables

    private void limpiarcampos() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
